<?php

return [
  'paths' => [
        'collections',
        'catalog',
        'studios',
        'search',
        'login',
        'register',
        'logout',
        'api',
        'admin',
        'page',
        'up',
        'profile',
        'favourites',
        'password',
        'genre',
        'country',
        'person',
        'year',
        'skoro',
        'theme-assets',
        '_admin-assets',
        'sitemap.xml',
        'robots.txt',
        'lander',
    ],
];
